events {}

http {

    upstream product_service {
        server product-service-green:8081;
    }

    upstream inventory_service {
        server inventory-service-green:8082;
    }

    upstream order_service {
        server order-service-green:8083;
    }

    server {

        listen 80;

        location /api/v1/products {
            proxy_pass http://product_service;

            proxy_set_header Host product-service-green;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/v1/inventories {
            proxy_pass http://inventory_service;

            proxy_set_header Host inventory-service-green;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/v1/orders {
            proxy_pass http://order_service;

            proxy_set_header Host order-service-green;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
location /monitor/product {
    proxy_pass http://product_service/monitor/active-requests;

    proxy_set_header Host product-service-green;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
location /monitor/inventory {
    proxy_pass http://inventory_service/monitor/active-requests;

    proxy_set_header Host inventory-service-green;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /monitor/order {
    proxy_pass http://order_service/monitor/active-requests;

    proxy_set_header Host order-service-green;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /actuator/product/health {
    proxy_pass http://product_service/actuator/health;

    proxy_set_header Host product-service-green;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /actuator/inventory/health {
    proxy_pass http://inventory_service/actuator/health;

    proxy_set_header Host inventory-service-green;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /actuator/order/health {
    proxy_pass http://order_service/actuator/health;

    proxy_set_header Host order-service-green;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

    }
}
