events {}

http {

    upstream product_service {
        server product-service:8081;
    }

    upstream inventory_service {
        server inventory-service:8082;
    }

    upstream order_service {
        server order-service:8083;
    }

    server {

        listen 80;

        location /api/v1/products {
            proxy_pass http://product_service;

            proxy_set_header Host product-service;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/v1/inventories {
            proxy_pass http://inventory_service;

            proxy_set_header Host inventory-service;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/v1/orders {
            proxy_pass http://order_service;

            proxy_set_header Host order-service;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

    }
}
