spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/inventory_service?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
server:
  port: ${SERVER_PORT:8082}
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
product-service:
  base-url: ${PRODUCT_SERVICE_URL:http://localhost:8081}
  connect-timeout-ms: ${PRODUCT_SERVICE_CONNECT_TIMEOUT_MS:2000}
  read-timeout-ms: ${PRODUCT_SERVICE_READ_TIMEOUT_MS:3000}
